INSERT INTO HEROI (id, nome, level, vida, ataque, defesa, historia, pocao, magia, imagem, logo, imgbatalha, pontos, status) VALUES (10, 'MESTRE', 100, 100, 100, 100, 'HISTÓRIA', 0, 0, '/Blacklist/img/heroiCompletoMestre.png', '/Blacklist/img/logoHeroiMestre.png', '/Blacklist/img/heroiBatalhaMestre.png', 50, 'VIVO');

INSERT INTO VILAO (id, nome, level, vida, ataque, defesa, historia, pocao, magia, imagem, logo, imgbatalha, posicao, status) VALUES (10, 'VILÃO10', 10, 42, 13, 12, 'HISTÓRIA', '1', '1', '/Blacklist/img/vilaoCompleto10.png', '/Blacklist/img/logoVilao10.png', '/Blacklist/img/vilaoBatalha10.png', '#10', 'VIVO');
INSERT INTO VILAO (id, nome, level, vida, ataque, defesa, historia, pocao, magia, imagem, logo, imgbatalha, posicao, status) VALUES (9, 'VILÃO9', 9, 39, 12, 11, 'HISTÓRIA', '1', '1', '/Blacklist/img/vilaoCompleto9.png', '/Blacklist/img/logoVilao9.png', '/Blacklist/img/vilaoBatalha9.png', '#9', 'VIVO');
INSERT INTO VILAO (id, nome, level, vida, ataque, defesa, historia, pocao, magia, imagem, logo, imgbatalha, posicao, status) VALUES (8, 'VILÃO8', 8, 36, 11, 10, 'HISTÓRIA', '1', '1', '/Blacklist/img/vilaoCompleto8.png', '/Blacklist/img/logoVilao8.png', '/Blacklist/img/vilaoBatalha8.png', '#8', 'VIVO');
INSERT INTO VILAO (id, nome, level, vida, ataque, defesa, historia, pocao, magia, imagem, logo, imgbatalha, posicao, status) VALUES (7, 'VILÃO7', 7, 33, 10, 9, 'HISTÓRIA', '1', '1', '/Blacklist/img/vilaoCompleto7.png', '/Blacklist/img/logoVilao7.png', '/Blacklist/img/vilaoBatalha7.png', '#7', 'VIVO');
INSERT INTO VILAO (id, nome, level, vida, ataque, defesa, historia, pocao, magia, imagem, logo, imgbatalha, posicao, status) VALUES (6, 'VILÃO6', 6, 30, 9, 8, 'HISTÓRIA', '1', '1', '/Blacklist/img/vilaoCompleto6.png', '/Blacklist/img/logoVilao6.png', '/Blacklist/img/vilaoBatalha6.png', '#6', 'VIVO');
INSERT INTO VILAO (id, nome, level, vida, ataque, defesa, historia, pocao, magia, imagem, logo, imgbatalha, posicao, status) VALUES (5, 'VILÃO5', 5, 27, 8, 7, 'HISTÓRIA', '1', '1', '/Blacklist/img/vilaoCompleto5.png', '/Blacklist/img/logoVilao5.png', '/Blacklist/img/vilaoBatalha5.png', '#5', 'VIVO');
INSERT INTO VILAO (id, nome, level, vida, ataque, defesa, historia, pocao, magia, imagem, logo, imgbatalha, posicao, status) VALUES (4, 'VILÃO4', 4, 24, 7, 6, 'HISTÓRIA', '1', '1', '/Blacklist/img/vilaoCompleto4.png', '/Blacklist/img/logoVilao4.png', '/Blacklist/img/vilaoBatalha4.png', '#4', 'VIVO');
INSERT INTO VILAO (id, nome, level, vida, ataque, defesa, historia, pocao, magia, imagem, logo, imgbatalha, posicao, status) VALUES (3, 'VILÃO3', 3, 21, 6, 5, 'HISTÓRIA', '1', '1', '/Blacklist/img/vilaoCompleto3.png', '/Blacklist/img/logoVilao3.png', '/Blacklist/img/vilaoBatalha3.png', '#3', 'VIVO');
INSERT INTO VILAO (id, nome, level, vida, ataque, defesa, historia, pocao, magia, imagem, logo, imgbatalha, posicao, status) VALUES (2, 'VILÃO2', 2, 18, 5, 4, 'HISTÓRIA', '1', '1', '/Blacklist/img/vilaoCompleto2.png', '/Blacklist/img/logoVilao2.png', '/Blacklist/img/vilaoBatalha2.png', '#2', 'VIVO');
INSERT INTO VILAO (id, nome, level, vida, ataque, defesa, historia, pocao, magia, imagem, logo, imgbatalha, posicao, status) VALUES (1, 'VILÃO1', 1, 15, 4, 3, 'HISTÓRIA', '1', '1', '/Blacklist/img/vilaoCompleto1.png', '/Blacklist/img/logoVilao1.png', '/Blacklist/img/vilaoBatalha1.png', '#1', 'VIVO');
